package pojos;
// Generated Oct 2, 2019 3:53:46 PM by Hibernate Tools 4.3.1



/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private int id;
     private String nama;
     private String email;
     private String alamat;

    public Customers() {
    }

    public Customers(int id, String nama, String email, String alamat) {
       this.id = id;
       this.nama = nama;
       this.email = email;
       this.alamat = alamat;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


